### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ShadowLoveElysia** [PlayVoice/so-vits-svc-5.0#129]

**Comment by ShadowLoveElysia** [comment]
Traceback (most recent call last):
  File "prepare/preprocess_speaker.py", line 12, in <module>
    from speaker.models.lstm import LSTMSpeakerEncoder
ModuleNotFoundError: No module named 'speaker'
root@autodl-container-2bb911bb3c-a7e5cde5:~/autodl-tmp/whisper-vits-svc-bigvgan-mix-v2# python prepare/preprocess_speaker.py data_svc/waves-16k/ data_svc/speaker -t 0
Traceback (most recent call last):
  File "prepare/preprocess_speaker.py", line 12, in <module>
    from speaker.config import SpeakerEncoderConfig
ModuleNotFoundError: No module named 'speaker'

**Comment by MaxMax2016** [comment]
检查下目录whisper-vits-svc-bigvgan-mix-v2/speaker 是否存在呢？

**Comment by ShadowLoveElysia** [comment]
你之前给我的爱莉mix推理包没有这个文件夹吧，我看github也没看到这个文件夹，这个文件夹有什么东西放里面

**Comment by MaxMax2016** [comment]
![speaker](https://github.com/PlayVoice/whisper-vits-svc/assets/16432329/c81f5768-946c-42d5-a793-68ae282f8718)
这个文件夹
