### ISSUE TITLE
希望后续能有WebUI  浏览器可以操作的界面

### ISSUE THREAD

**Issue by TomYule** [PlayVoice/so-vits-svc-5.0#139]
希望后续能有WebUI  浏览器可以操作的界面

**Comment by MaxMax2016** [comment]
python app.py 就是启动webUI吧

**Comment by rkuo2000** [comment]
python app.py
Ready
Traceback (most recent call last):
  File "/home/rkuo/so-vits-svc-5.0/app.py", line 444, in <module>
    webui = WebUI()
  File "/home/rkuo/so-vits-svc-5.0/app.py", line 26, in __init__
    self.main_ui()
  File "/home/rkuo/so-vits-svc-5.0/app.py", line 127, in main_ui
    self.input_wav = gr.Audio(type='filepath', label=i18n('选择待转换音频'), source='upload')
  File "/home/rkuo/.local/lib/python3.10/site-packages/gradio/component_meta.py", line 157, in wrapper
    return fn(self, **kwargs)
TypeError: Audio.__init__() got an unexpected keyword argument 'source'
