### ISSUE TITLE
what is the reason for this?

### ISSUE THREAD

**Issue by ghostly4004** [PlayVoice/so-vits-svc-5.0#14]
I installed everything that was in the file requirements.txt , but it gives me this error at stage 4
I also exported PYTHONPATH (I got to stage 7, except stage 4, with no errors)

Traceback (most recent call last):
  File "prepare/preprocess_ppg.py", line 54, in <module>
    pred_ppg(whisper, f"{wavPath}/{spks}/{file}.wav", f"{ppgPath}/{spks}/{file}.ppg")
  File "prepare/preprocess_ppg.py", line 20, in pred_ppg
    audio = load_audio(wavPath)
  File "so-vits-svc-5.0-main\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
   File "Python\Python38\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "Python\Python38\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    
FileNotFoundError: [WinError 2] The specified file cannot be found

**Comment by MaxMax2016** [comment]
the wave path is error?
