### ISSUE TITLE
incorrect audio shape

### ISSUE THREAD

**Issue by gjp4tw** [PlayVoice/so-vits-svc-5.0#15]
執行  python prepare/preprocess_ppg.py -w data_svc/waves-16k/ -p data_svc/whisper後出現此錯誤
![image](https://user-images.githubusercontent.com/59504270/236200031-c7961d46-3183-444f-a86d-d883c85af81d.png)

請問要怎麼解決

**Comment by MaxMax2016** [comment]
whisper要求音频小于30秒

**Comment by xiaobaozi233** [comment]
我是碰到了这个，请问是啥原因啊？
Traceback (most recent call last):
  File "prepare/preprocess_ppg.py", line 57, in <module>
    pred_ppg(whisper, f"{wavPath}/{spks}/{file}.wav", f"{ppgPath}/{spks}/{file}.ppg")
  File "prepare/preprocess_ppg.py", line 26, in pred_ppg
    ppg = whisper.encoder(mel.unsqueeze(0)).squeeze().data.cpu().float().numpy()
  File "C:\Users\*\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\*\whisper\model.py", line 166, in forward
    assert x.shape[1:] == self.positional_embedding.shape, "incorrect audio shape"
AssertionError: incorrect audio shape

**Comment by MaxMax2016** [comment]
您用的官方whisper吧，官方whisper短音频必须要拼接静音、使得长度等于30S；仓库略微修改代码，短音频小于30S不用拼接。

>         len_x = x.shape[1]
>         len_e = self.positional_embedding.shape[0]
>         assert len_x <= len_e, "incorrect audio shape"

**Comment by xiaobaozi233** [comment]
> 您用的官方whisper吧，官方whisper短音频必须要拼接静音、使得长度等于30S；仓库略微修改代码，短音频小于30S不用拼接。
> 
> > ```
> >     len_x = x.shape[1]
> >     len_e = self.positional_embedding.shape[0]
> >     assert len_x <= len_e, "incorrect audio shape"
> > ```

解决了~感谢

**Comment by LiuNoCap** [comment]
大佬 具体修改哪一个文件
