### ISSUE TITLE
这是为什么？因为版本的问题么，我的crepe是0.0.14。

### ISSUE THREAD

**Issue by TMD1122** [PlayVoice/so-vits-svc-5.0#163]
PS D:\4399TMD\python\Project\so-vits-svc-5.0-bigvgan-mix-v2> python prepare/preprocess_crepe.py -w data_svc/waves-16k/ -p data_svc/pitch
data_svc/waves-16k/
data_svc/pitch
Processing crepe speaker0:   0%|                                                               | 0/345 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "D:\4399TMD\python\Project\so-vits-svc-5.0-bigvgan-mix-v2\prepare\preprocess_crepe.py", line 69, in <module>
    compute_f0(f"{wavPath}/{spks}/{file}.wav", f"{pitPath}/{spks}/{file}.pit", device)
  File "D:\4399TMD\python\Project\so-vits-svc-5.0-bigvgan-mix-v2\prepare\preprocess_crepe.py", line 28, in compute_f0
    pitch, periodicity = crepe.predict(
                         ^^^^^^^^^^^^^^
TypeError: predict() got an unexpected keyword argument 'batch_size'
PS D:\4399TMD\python\Project\so-vits-svc-5.0-bigvgan-mix-v2>

**Comment by TMD1122** [comment]
找到问题了，我自己安装了crepe。但其实是不需要安装的，uninstall就好了。
