### ISSUE TITLE
ModuleNotFoundError: No module named 'whisper'

### ISSUE THREAD

**Issue by DumoeDss** [PlayVoice/so-vits-svc-5.0#18]
调用`python whisper/inference.py -w test.wav -p test.ppg.npy` 报错无whisper模块
pip install whisper之后报错、

> Traceback (most recent call last):
  File "H:\svc\sovits\so-vits-svc-5.0\whisper\inference.py", line 6, in <module>
    from whisper.model import Whisper, ModelDimensions
  File "H:\svc\sovits\so-vits-svc-5.0\venv\lib\site-packages\whisper.py", line 65, in <module>
    libc = ctypes.CDLL(libc_name)
  File "C:\Python310\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by MaxMax2016** [comment]
不用安装它，代码集成和修改了whisper

**Comment by MaxMax2016** [comment]
1， 设置工作目录

export PYTHONPATH=$PWD
