### ISSUE TITLE
错误 [WinError 183] 当文件已存在时，无法创建该文件。

### ISSUE THREAD

**Issue by thestmitsuki** [PlayVoice/so-vits-svc-5.0#23]
运行代码  重采样

将音频剪裁为小于30秒的音频段，whisper的要求

生成采样率16000Hz音频, 存储路径为：./data_svc/waves-16k

python prepare/preprocess_a.py -w ./data_raw -o ./data_svc/waves-16k -s 16000
后，出现 [WinError 3] 系统找不到指定的路径。
但翻看文件夹时，对应文件已存在
再次运行代码  [WinError 183] 当文件已存在时，无法创建该文件。
但是文件夹中并没有采样率16000HZ的音频段，一片空白

**Comment by MaxMax2016** [comment]
第二次运行程序，会提示文件已存在，特意这样设计的，避免误操作覆盖原数据。要再次运行程序，需要提前手动删除目标文件夹。

**Comment by MaxMax2016** [comment]
1， 设置工作目录💗💗💗不设置后面会报错

export PYTHONPATH=$PWD

**Comment by MaxMax2016** [comment]
./data_raw里面放了多少音频呢？

**Comment by MaxMax2016** [comment]
我在win上面尝试，根据错误提示进行修改，逐个跑下来没复现到问题
```
C:\Users\admin\Desktop\so-vits-svc-5.0-main> python prepare/preprocess_a.py -w ./data_raw -o ./data_svc/waves-16k -s 16000
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\so-vits-svc-5.0-main\prepare\preprocess_a.py", line 2, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'
PS C:\Users\admin\Desktop\so-vits-svc-5.0-main> python prepare/preprocess_a.py -w ./data_raw -o ./data_svc/waves-16k -s 16000
./data_raw
./data_svc/waves-16k
16000
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\so-vits-svc-5.0-main\prepare\preprocess_a.py", line 31, in <module>
    for spks in os.listdir(wavPath):
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: './data_raw'
PS C:\Users\admin\Desktop\so-vits-svc-5.0-main> python prepare/preprocess_a.py -w ./data_raw -o ./data_svc/waves-16k -s 16000
./data_raw
./data_svc/waves-16k
16000
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\so-vits-svc-5.0-main\prepare\preprocess_a.py", line 25, in <module>
    os.makedirs(args.out)
  File "D:\Program Files\Python\Python3.10\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: './data_svc/waves-16k'
PS C:\Users\admin\Desktop\so-vits-svc-5.0-main> python prepare/preprocess_a.py -w ./data_raw -o ./data_svc/waves-16k -s 16000
./data_raw
./data_svc/waves-16k
16000
>>>>>>>>>>11<<<<<<<<<<
./data_svc/waves-16k/11/test.wav
```

**Comment by MaxMax2016** [comment]
您的音频文件后缀是.wav吗？
