### ISSUE TITLE
浅扩散推理时扩散模型无法识别，不带扩散模型可正常推理（linux）

### ISSUE THREAD

**Issue by KIKscanf** [PlayVoice/so-vits-svc-5.0#36]
./raw/test.wav
test.ppg.npy
./raw/test.wav
test.csv
don't use pitch shift
/root/autodl-tmp/so-vits-svc5/diff_tool
No diffusion model or config found. Shallow diffusion mode will False
Traceback (most recent call last):
  File "inference_main.py", line 121, in <module>
    main()
  File "inference_main.py", line 83, in main
    svc_model = Svc(args.model_path, args.config_path, args.device, args.cluster_model_path,enhance,diffusion_model_path,diffusion_config_path,shallow_diffusion,only_diffusion)
  File "/root/autodl-tmp/so-vits-svc5/diff_tool/inference/infer_tool.py", line 159, in __init__
    self.load_model()
  File "/root/autodl-tmp/so-vits-svc5/diff_tool/inference/infer_tool.py", line 176, in load_model
    self.hps_ms.data.filter_length // 2 + 1,
AttributeError: 'Svc' object has no attribute 'hps_ms'
/root/autodl-tmp/so-vits-svc5
mv: cannot stat './diff_tool/results/*': No such file or directory
推理结束

**Comment by MaxMax2016** [comment]
您需要联系您使用的autodl项目的作者，这个github项目没有浅扩散模块

**Comment by KIKscanf** [comment]
好的，谢谢
