### ISSUE TITLE
issue in step 4 of Data preprocessing

### ISSUE THREAD

**Issue by Parisa-Bagherzadeh** [PlayVoice/so-vits-svc-5.0#45]
i get this error when running this : python prepare/preprocess_ppg.py -w data_svc/waves-16k/ -p data_svc/whisper

Traceback (most recent call last):
  File "prepare/preprocess_ppg.py", line 56, in <module>
    whisper = load_model(os.path.join("whisper_pretrain", "medium.pt"))
  File "prepare/preprocess_ppg.py", line 25, in load_model
    dims = ModelDimensions(**checkpoint["dims"])
TypeError: 'ModuleSpec' object is not callable

**Comment by Parisa-Bagherzadeh** [comment]
> is there more detial log info?

it's all the error after running step 4 of data preprocessing
data_svc/waves-16k/
data_svc/whisper
Traceback (most recent call last):
  File "prepare/preprocess_ppg.py", line 56, in <module>
    whisper = load_model(os.path.join("whisper_pretrain", "medium.pt"))
  File "prepare/preprocess_ppg.py", line 25, in load_model
    dims = ModelDimensions(**checkpoint["dims"])
TypeError: 'ModuleSpec' object is not callable

**Comment by MaxMax2016** [comment]
your code is different from this project, line 25 is " audln = audio.shape[0]"

**Comment by Parisa-Bagherzadeh** [comment]
> your code is different from this project, line 25 is " audln = audio.shape[0]"

oh yes you're right it's different , but i cloned the repo yesterday
i don't know why it's different !

So i copied the code from the file preprocess_ppg.py but i got this error this time :/

data_svc/waves-16k/
data_svc/whisper
>>>>>>>>>>speaker0<<<<<<<<<<
Traceback (most recent call last):
  File "/home/parisa/so-vits-svc-5.0_/whisper/audio.py", line 44, in load_audio
    ffmpeg.input(file, threads=0)
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prepare/preprocess_ppg.py", line 58, in <module>
    pred_ppg(whisper, f"{wavPath}/{spks}/{file}.wav", f"{ppgPath}/{spks}/{file}.ppg")
  File "prepare/preprocess_ppg.py", line 24, in pred_ppg
    audio = load_audio(wavPath)
  File "/home/parisa/so-vits-svc-5.0_/whisper/audio.py", line 48, in load_audio
    except ffmpeg.Error as e:
AttributeError: module 'ffmpeg' has no attribute 'Error'
