### ISSUE TITLE
import module

### ISSUE THREAD

**Issue by Parisa-Bagherzadeh** [PlayVoice/so-vits-svc-5.0#46]
how should i solve this error?
ModuleNotFoundError: No module named 'whisper.model'; 'whisper' is not a package

**Comment by MaxMax2016** [comment]
whisper is built-in, do not install it additionally, it will conflict and report an error

set working directory:

export PYTHONPATH=$PWD

**Comment by Parisa-Bagherzadeh** [comment]
> whisper is built-in, do not install it additionally, it will conflict and report an error
> 
> set working directory:
> 
> export PYTHONPATH=$PWD

thank you , it works but another errors happened :

Traceback (most recent call last):
  File "prepare/preprocess_ppg.py", line 62, in <module>
    pred_ppg(whisper, f"{wavPath}/{spks}/{file}.wav", f"{ppgPath}/{spks}/{file}.ppg")
  File "prepare/preprocess_ppg.py", line 34, in pred_ppg
    ppg = whisper.encoder(mel.unsqueeze(0)).squeeze().data.cpu().float().numpy()
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/parisa/so-vits-svc-5.0_/whisper/model.py", line 159, in forward
    x = block(x)
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/parisa/so-vits-svc-5.0_/whisper/model.py", line 124, in forward
    x = x + self.attn(self.attn_ln(x), mask=mask, kv_cache=kv_cache)[0]
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/parisa/so-vits-svc-5.0_/whisper/model.py", line 30, in forward
    return super().forward(x.float()).type(x.dtype)
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/torch/nn/modules/normalization.py", line 191, in forward
    input, self.normalized_shape, self.weight, self.bias, self.eps)
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Float but found Half

**Comment by MaxMax2016** [comment]
you need update codes, and need a GPU.

**Comment by Parisa-Bagherzadeh** [comment]
> you need update codes, and need a GPU.

i got this error after running the fifth step of inference 

Traceback (most recent call last):
  File "svc_inference.py", line 169, in <module>
    main(args)
  File "svc_inference.py", line 51, in main
    load_svc_model(args.model, model)
  File "svc_inference.py", line 17, in load_svc_model
    assert os.path.isfile(checkpoint_path)
AssertionError

**Comment by MaxMax2016** [comment]
do you downward the checkpoint of the model, and set the right path?

**Comment by Parisa-Bagherzadeh** [comment]
> do you downward the checkpoint of the model, and set the right path?

Whrere are the checkpoints of the model ?

**Comment by MaxMax2016** [comment]
in readme

**Comment by R0jER5** [comment]
I have downloaded the model and saved it in whisper_pretrain as per readme.

But still getting this error:
https://github.com/PlayVoice/so-vits-svc-5.0/issues/46#issuecomment-1595639115
