### ISSUE TITLE
Error in step 5 of data preprocess

### ISSUE THREAD

**Issue by Parisa-Bagherzadeh** [PlayVoice/so-vits-svc-5.0#63]
How to fix this?

> Setting up Audio Processor...
 | > sample_rate:16000
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:-100
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:20
 | > fft_size:1024
 | > power:1.5
 | > preemphasis:0.98
 | > griffin_lim_iters:60
 | > signal_norm:True
 | > symmetric_norm:True
 | > mel_fmin:0
 | > mel_fmax:8000.0
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:4.0
 | > clip_norm:True
 | > do_trim_silence:True
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 49%|████████████████████████████████████████████████▌                                                  | 200/408 [00:11<00:12, 17.05it/s]/home/parisa/so-vits-svc-5.0__/speaker/utils/audio.py:732: RuntimeWarning: invalid value encountered in true_divide
  return x / abs(x).max() * 0.95
 49%|████████████████████████████████████████████████▌                                                  | 200/408 [00:11<00:11, 17.49it/s]
Traceback (most recent call last):
  File "prepare/preprocess_speaker.py", line 79, in <module>
    spec = speaker_encoder_ap.melspectrogram(waveform)
  File "/home/parisa/so-vits-svc-5.0__/speaker/utils/audio.py", line 564, in melspectrogram
    D = self._stft(self.apply_preemphasis(y))
  File "/home/parisa/so-vits-svc-5.0__/speaker/utils/audio.py", line 624, in _stft
    center=True,
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/librosa/core/spectrum.py", line 202, in stft
    util.valid_audio(y, mono=False)
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/home/parisa/anaconda3/envs/voice/lib/python3.7/site-packages/librosa/util/utils.py", line 294, in valid_audio
    raise ParameterError("Audio buffer is not finite everywhere")
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere

**Comment by MaxMax2016** [comment]
delete the error wave.
https://stackoverflow.com/questions/57097840/librosa-parametererror-audio-buffer-is-not-finite-everywhere-cutting-wav-files

**Comment by Parisa-Bagherzadeh** [comment]
> delete the error wave. https://stackoverflow.com/questions/57097840/librosa-parametererror-audio-buffer-is-not-finite-everywhere-cutting-wav-files

Thank you for answers
